### ISSUE TITLE
youtube_bash_dl.sh   wget: missing URL

### ISSUE THREAD

**Issue by cirrusUK** [paralllax/libash#1]
Not so much an issue but just a heads up as to the wget: missing URL error when i run the function as is, modifying it like so at least downloads the video.
.
- 	    | xargs -I{} wget -q -O ${file_name} {}

+	   read -p "enter name of video: " video

+	    | xargs -I{} wget -q -O ${video}.mp4 {}

seems to be best way of file naming ive got working, ofc it needs user input, but hey its an option i modified the function into a shell script [_wgetyt_](https://paste.xinu.at/8HCx5/)

**Comment by paralllax** [comment]
Thanks for raising this! Nice script. I debating expanding the function (accept playlists, mutliple videos, etc...), but since youtube_dl still exists, not sure if I will. 

In any case, my apologies, I don't think I follow. Could you post an example of the error and video you used? The syntax of the fix you suggested is more or less the same as the existing code. 

For me the current version works.

```
17:38[parallax]═╬═╬╩╦╬╧[Devastator[libash]$ youtube_bash_dl "https://www.youtube.com/watch?v=LCmsrVOXzZc" test-footage.mp4
test-footage.mp4 -- Downloaded
17:39[parallax]═╬═╬╩╦╬╧[Devastator[libash]$ file test-footage.mp4
test-footage.mp4: ISO Media, MP4 v2 [ISO 14496-14]
```

I am curious if maybe we have different versions

```
17:44[parallax]═╬═╬╩╦╬╧[Devastator[libash]$ xargs --version | sed -n 1p
xargs (GNU findutils) 4.7.0
17:44[parallax]═╬═╬╩╦╬╧[Devastator[libash]$ wget --version | sed -n 1p
GNU Wget 1.20.3 built on linux-gnu.
```

When you rerun the command, would you mind putting `set +x` at the top of the function, or before you run the function, run `bash -x` to launch a bash shell in debug mode?

If you have any other questions let me know. Thank you!

**Comment by cirrusUK** [comment]
yes indeed it is more or less the same as original code but for whatever reason wget throws out missing URL unless i adapt them couple of lines, i originally used ${RANDOM}.mp4 but settled on  read -p "" instead of random numbers.mp4

xargs (GNU findutils) 4.7.0
GNU Wget 1.20.3 built on linux-gnu.

after sourcing libash..sh ....... 
youtube_bash_dl 'https://www.youtube.com/watch?v=sjoepLlVL6o'
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

My only difference maybe the fact i used a[ _prebuilt pup pkg_ ](https://github.com/ericchiang/pup/releases)as the HDD space is sparse so id rather not install go
same scenario with bash -x & if adapt the original function into a script.
regards & thx for the code
 DISREGARD ALL OF ABOVE I AM AN IDIOT !  As you can see above i wasn not using correct syntax i was missing the 'myfile.mp4' 
really sorry for the noise.

**Comment by paralllax** [comment]
Nice! If you wanted, you could do something like this too. It makes a pre-named unique file.

`video=$(mktemp)`

ah I see, thank you for providing the output! You will need to add the file name after the URL. :)

`youtube_bash_dl 'https://www.youtube.com/watch?v=sjoepLlVL6o' 'what-i-want-to-name-it.mp4'`

I imagine the wget thought the URL was the name of the file since the variable was empty

Yeah for sure! Thank you for using it!

**Comment by paralllax** [comment]
Ah sorry just saw your edits! haha don't even worry man, it happens. I've never had an issue raised before, and it was fun, so thank you! Don't ever feel bad and don't be hard on yourself :)
